version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/audio_transcribe"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/audio_transcribe/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/audio_transcribe_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/audio_transcribe_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/audio_transcribe_ios"
    schedule:
      interval: "daily"