name: audio_transcribe_ios
description: iOS implementation of the audio_transcribe plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  plugin:
    implements: audio_transcribe
    platforms:
      ios:
        pluginClass: AudioTranscribePlugin
        dartPluginClass: AudioTranscribeIOS

dependencies:
  flutter:
    sdk: flutter
  audio_transcribe_platform_interface:
    path: ../audio_transcribe_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^6.0.0
